/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ApprovalUserQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "createUser": {
      "name": string
      "type": "sst.aws.Function"
    }
    "deleteUser": {
      "name": string
      "type": "sst.aws.Function"
    }
    "getUser": {
      "name": string
      "type": "sst.aws.Function"
    }
    "listUsers": {
      "name": string
      "type": "sst.aws.Function"
    }
    "login": {
      "name": string
      "type": "sst.aws.Function"
    }
    "registerUser": {
      "name": string
      "type": "sst.aws.Function"
    }
    "updateUser": {
      "name": string
      "type": "sst.aws.Function"
    }
    "userApprovalTriggerFn": {
      "name": string
      "type": "sst.aws.Function"
    }
    "validateUser": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}